app/weather/models.py
from peewee import CharField, TextField, ForeignKeyField

from app.base_model import BaseModel
from app.auth.models import User
from app.exceptions import ValidationError


class Country(BaseModel):
    code = CharField(max_length=3, unique=True, index=True)
    name = CharField(max_length=150, unique=True, index=True)
    flag = CharField(unique=True)
    description = TextField()

    def to_json(self):
        country = {
            'id': self.id,
            'code': self.code,
            'name': self.name,
            'flag': self.flag,
            'description': self.description}
        return country


class City(BaseModel):
    name = CharField(max_length=150, unique=True, index=True)
    country = ForeignKeyField(Country, backref='city')

    def to_json(self):
        city = {
            'id': self.id,
            'name': self.name,
            'country_id': self.country.id,
            'country_name': self.country.name}
        return city

    @staticmethod
    def from_json(city_json):
        name = city_json.get('name')
        if not name:
            raise ValidationError('city does not have a name')

        name = name.capitalize()
        city_exist = City.select().where(City.name == name).first()
        if city_exist:
            raise ValidationError(f'city {city_exist.name} already added in database with id {city_exist.id}')

        return City(name=name)


class UserCity(BaseModel):
    city = ForeignKeyField(City, backref='city_user')
    user = ForeignKeyField(User, backref='city_user')

app/weather/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class CityForm(FlaskForm):
    city_name = StringField(
        'What city are you interested in?',
        validators=[DataRequired(), Length(3, 150)],
        render_kw={'placeholder': 'City name'}
    )
    submit = SubmitField('Show')

app/weather/__init__.py
from flask import Blueprint

weather = Blueprint('weather', __name__, url_prefix='/weather')

from app.weather import routes

app/weather/routes.py
from flask import render_template, current_app, flash, redirect, url_for, request, abort
from flask_login import current_user, login_required

from app.weather import weather
from app.weather.forms import CityForm
from utils.weather.city_weather import main as get_weather
from utils.ip.get_current_city import main as get_current_city
from app.weather.models import City, Country, UserCity
from app.auth.models import User


@weather.route('/', methods=['GET', 'POST'])
def index():
    form = CityForm()
    city_weather = None
    city_name = get_current_city()
    country = None

    if form.validate_on_submit():
        api_key = current_app.config['WEATHER_API_KEY']
        city_name = form.city_name.data
        city_weather = get_weather(city_name, api_key)

        if 'message' in city_weather:
            flash(city_weather['message'])
            return redirect(url_for('.index'))

        country = Country.select().where(Country.code == city_weather['country']).first()
        if not country:
            flash('Country not found')
            return redirect('.index')

    return render_template(
        'weather/get_weather.html',
        title='Show weather info',
        form=form,
        city_weather=city_weather,
        city_name=city_name,
        country=country
    )


@weather.route('/city/add', methods=['POST'])
@login_required
def add_city():
    city_name = request.form.get('city').capitalize()

    city = City.select().where(City.name == city_name).first()
    if not city:
        country = request.form.get('country')
        city = City(name=city_name,
                    country=country)
        city.save()

    user_city = UserCity.select().where(UserCity.user == current_user, UserCity.city == city).first()
    if user_city:
        flash(f'City {city_name} already in list of user {current_user.username}')
        return redirect(url_for('.index'))

    user_city = UserCity(user=current_user, city=city)
    user_city.save()

    flash(f'City {city_name} added to user {current_user.username}')
    return redirect(url_for('.index'))


@weather.route('/city/show', methods=['GET'])
@login_required
def show_city():
    user_cities = (
        UserCity
        .select(City)
        .join(User)
        .switch(UserCity)
        .join(City)
        .where(UserCity.user == current_user)
        .order_by(City.name)
    )

    country_name = request.args.get('country')
    if country_name:
        user_cities = [user_city for user_city in user_cities if user_city.city.country.name == country_name]

    return render_template(
        'weather/show_user_cities.html',
        title=f'Cities of {current_user.username}',
        cities=user_cities)


@weather.route('/city/show/<string:city_name>', methods=['GET'])
@login_required
def show_city_detail(city_name: str):
    api_key = current_app.config['WEATHER_API_KEY']
    city_name = city_name.capitalize()

    user_city = (
        UserCity
        .select(City)
        .join(User)
        .where(User.id == current_user.id)
        .switch(UserCity)
        .join(City)
        .where(City.name == city_name).first()
    )

    if not user_city:
        abort(404)

    city_weather = get_weather(user_city.city.name, api_key)
    if 'message' in city_weather:
        flash(city_weather['message'])
        return redirect(url_for('.index'))

    return render_template(
        'weather/show_user_city_detail.html',
        title=f'Weather info about {user_city.city.name}',
        city_weather=city_weather,
        country=user_city.city.country
    )


@weather.route('/city/delete', methods=['POST'])
@login_required
def delete_city():
    selectors = list(map(int, request.form.getlist('selectors')))

    if not selectors:
        flash('Nothing to delete')
        return redirect(url_for('.show_city'))

    (UserCity
     .delete()
     .where(UserCity.user == current_user, UserCity.city.in_(selectors)).execute())

    cities_to_delete = City.select().where(City.id.in_(selectors)).order_by(City.name)
    message = 'Delete: '
    for city in cities_to_delete:
        message += f'{city.name}, '

    flash(message[:-2])
    return redirect(url_for('.show_city'))

app/templates/weather/_weather_table.html
<table class="table table-hover table-striped">
  <thead>
  <tr>
    <th scope="col">Field</th>
    <th scope="col">Value</th>
  </tr>
  </thead>
  <tbody>
  {% for field, value in city_weather.items() %}
    <tr>
      <td>{{ field.capitalize() }}</td>
      {% if field == 'icon_url' %}
      <td class="bg-info"><img src="{{ value }}" alt="weather condition icon"></td>
      {% else %}
      <td>{{ value }}</td>
      {% endif %}
    </tr>
  {% endfor %}
  </tbody>
</table>

app/templates/weather/get_weather.html
{% extends '_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block page_content %}
<div class="page-header">
  <h1>Show weather info about city</h1>
  {% include 'messages.html' %}
</div>

<div class="col-md-4">
  <form action="" method="post">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.city_name) }}
    {{ wtf.form_field(form.submit) }}
  </form>

  {% if city_weather %}
  <div class="table-responsive">
    <h3>Weather info about city {{ city_name.capitalize() }}, {{ country.name }}</h3>
    {% include 'weather/_weather_table.html' %}
    <form action="{{ url_for('weather.add_city') }}" method="post">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <input type="hidden" name="city" value="{{ city_name }}">
      <input type="hidden" name="country" value="{{ country }}">
      <button type="submit" class="btn btn-primary" id="addCity">Add city</button>
    </form>
  </div>
  {% endif %}
</div>
  <div class="col-md-5">
     <div class="gmap_canvas">
       <iframe width="400" height="300" id="gmap_canvas"
               src="https://maps.google.com/maps?q={{ city_name }}&t=&z=9&ie=UTF8&iwloc=&output=embed">
       </iframe>
     </div>
   </div>
{% endblock page_content %}

app/templates/weather/show_user_cities.html
{% extends '_base.html' %}

{% block page_content %}
<div class="page-header">
  <h1>Users cities</h1>
</div>
{% include 'messages.html' %}

<button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">Select all</button>
<button type="submit" class="btn btn-danger" form="citiesForm" id="deleteButton">Delete</button>
<hr>

<form action="{{ url_for('weather.delete_city') }}" method="post" id="citiesForm">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  <div class="table-responsive col-md-4">
    <table class="table table-hover table-striped" id="citiesTable">
      <thead>
      <tr>
        <th class="col">Select</th>
        <th class="col">#</th>
        <th class="col">City</th>
        <th class="col">Country</th>
        <th class="col">Flag</th>
      </tr>
      </thead>
      <tbody>
      {% for user_city in cities %}
      <tr>
        <td>
          <input type="checkbox" name="selectors" class="checkbox" value="{{ user_city.city.id }}">
        </td>
        <td>{{ loop.index }}</td>
        <td>
          <a href="{{ url_for('weather.show_city_detail', city_name=user_city.city.name) }}">
            {{ user_city.city.name }}
          </a>
        </td>
        <td>
          <a href="{{ url_for('weather.show_city', country=user_city.city.country.name) }}">
            {{ user_city.city.country.name }}
          </a>
        </td>
        <td class="bg-info"><img src="{{ user_city.city.country.flag }}" alt="" width="60" height="40"></td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</form>
{% endblock page_content %}


app/templates/weather/show_user_city_detail.html
{% extends '_base.html' %}

{% block page_content %}
<div class="page-header">
  <h1>{{ title }}</h1>
</div>

<div class="table-responsive col-md-4">
    {% include 'weather/_weather_table.html' %}
</div>

<div class="table-responsive col-md-4">
    <h3>Country {{ country.name }}</h3>
    <p><img src="{{ country.flag }}" alt=""></p>
    <p>{{ country.description }}</p>
</div>
{% endblock page_content %}