app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, HiddenField, StringField, SelectField
from wtforms.validators import DataRequired, Length, Regexp, Email


class GenerateDataForm(FlaskForm):
    qty = SelectField(
        'Quantity',
        validators=[DataRequired()],
        choices=[10, 15, 25]
    )
    submit = SubmitField('Generate')


class EditUserForm(FlaskForm):
    id = HiddenField()
    username = StringField(
        'Edit username',
        validators=[
            DataRequired(),
            Length(3, 100),
            Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, 'Username must contains only letters, underscores or digits')
        ],
        render_kw={'placeholder': 'Enter your name'}
    )
    email = StringField(
        'Email',
        validators=[
            DataRequired(),
            Length(10, 200),
            Email()
        ]
    )
    submit = SubmitField('Edit')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request, abort
from flask_login import current_user, login_required
from flask_paginate import get_parameter, Pagination

from app import User, Profile
from app.main import main
from app.main.forms import GenerateDataForm, EditUserForm
from utils.fake_users.db_manager import main as write_fake_profiles


@main.route('/', methods=['GET', 'POST'])
def index():
    form = GenerateDataForm()
    if form.validate_on_submit():
        qty = int(form.qty.data)
        write_fake_profiles(qty)
        flash('Database filled with test data')
    return render_template(
        'main/index.html',
        title='Home page',
        form=form
    )


@main.route('/show/users')
@login_required
def show_users():
    """Show users information"""
    per_page = 10
    page = request.args.get(get_parameter(), type=int, default=1)
    total = User.select().count()
    pagination = Pagination(page=page, per_page=per_page, total=total, record_name='users')

    users = User.select().paginate(page, per_page)
    return render_template(
        'main/show_users.html',
        title='Show users',
        users=users,
        pagination=pagination)


@main.route('/edit/user/<int:user_id>', methods=['GET'])
@login_required
def edit_user(user_id: int):
    """Edit user"""
    if not current_user.is_admin():
        abort(403)

    user = User.select().where(User.id == user_id).first()
    if not user:
        abort(404)

    form = EditUserForm()
    form.id.label.text = ''
    form.id.data = user.id
    form.username.data = user.username
    form.email.data = user.email
    return render_template(
        'main/edit_user.html',
        title=f'Edit user {user.username}',
        form=form
    )


@main.route('/update/user', methods=['POST'])
@login_required
def update_user():
    form = EditUserForm()
    if form.validate_on_submit():
        user = User.get(User.id == int(form.id.data))
        user.username = form.username.data.strip().lower()
        user.email = form.email.data.strip().lower()
        user.save()
        flash(f'{user.username} updated')
    else:
        flash(form.errors)
    return redirect(url_for('.show_users'))


@main.route('/delete/users', methods=['POST'])
@login_required
def delete_users():
    """Delete selected users"""
    if not current_user.is_admin():
        flash('You don\'t have access to delete users', 'error')
        return redirect(url_for('.show_users'))

    selectors = list(map(int, request.form.getlist('selectors')))

    if current_user.id in selectors:
        flash('You can\'t delete yourself use profile page for this')
        return redirect(url_for('.show_users'))

    if not selectors:
        flash('Nothing to delete')
        return redirect(url_for('.show_users'))

    message = 'Deleted: '
    for selector in selectors:
        user = User.get(User.id == selector)
        profile = Profile.get(Profile.id == user.profile.id)
        message += f'{user.email} '
        user.delete_instance()
        profile.delete_instance()
    flash(message)
    return redirect(url_for('.show_users'))

app/templates/main/edit_user.html
{% extends '_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block page_content %}
<div class="page-header">
  <h1>{{ title }}</h1>
</div>
{% include 'messages.html' %}
<div class="col-md-4">
  <form action="{{ url_for('main.update_user') }}" method="post">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.id) }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.submit) }}
  </form>
</div>


{% endblock page_content %}

app/templates/main/index.html
{% extends '_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block page_content %}
<div class="page-header">
  <h1>Hello,
    {% if current_user.is_authenticated %}
    {{ current_user.username }}
    {% else %}
    Anonymous
    {% endif %}
  </h1>
</div>
<h3>Generate test data</h3>
{% include 'messages.html' %}
<h3>{{ message }}</h3>
<form action="" method="post" class="col-md-1">
  {{ form.csrf_token }}
  {{ wtf.form_field(form.qty) }}
  {{ wtf.form_field(form.submit) }}
</form>

{% endblock page_content %}

app/templates/main/show_users.html
{% extends '_base.html' %}

{% block page_content %}
<div class="page-header">
  <h1>Users admin panel</h1>
</div>
{% include 'messages.html' %}

<button type="button" class="btn btn-primary" id="selectButton" onclick="toggle()">Select all</button>
<button type="submit" class="btn btn-danger" form="userForm" id="deleteButton">Delete</button>
<hr>
{{ pagination.info }}
{{ pagination.links }}

<form action="{{ url_for('main.delete_users') }}" method="post" id="userForm">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  <div class="table-responsive">
    <table class="table table-hover table-striped" id="userTable">
      <thead>
      <tr>
        <th class="col">Select</th>
        <th class="col">Username</th>
        <th class="col">Email</th>
        <th class="col">Role</th>
        <th class="col">Edit</th>
      </tr>
      </thead>
      <tbody>
      {% for user in users %}
      <tr>
        <td>
          <input type="checkbox" name="selectors" class="checkbox" value="{{ user.id }}">
        </td>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.role.name }}</td>
        <td>
          <a href="{{ url_for('main.edit_user', user_id=user.id) }}" id="editLink">
            <button type="button" class="btn btn-info">Edit</button>
          </a>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</form>

{% endblock page_content %}